global:  
  scrape_interval:  15s   

scrape_configs:  

      - job_name: 'prometheusY'  
        static_configs: 
             - targets: ['prometheusY:9091']

      - job_name: 'federate'
        scrape_interval: 15s

        honor_labels: true
        metrics_path: '/federate'

        params:
          match[]:
            - '{job="node-exporter"}'

        static_configs:
             - targets:
                - 'prometheusX:9090'

