global:  
  scrape_interval:  15s   

scrape_configs: 
    
      - job_name: 'prometheusX'  
        static_configs: 
             - targets: ['prometheusX:9090']

      - job_name: 'node-exporter'
        static_configs:
             - targets: ['node-exporter:9100']
