global:
  resolve_timeout: 15s

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 3h 
  receiver: 'default'

receivers:
- name: 'default'
  email_configs:
  - to: quynh.vuongg@gmail.com
    from: quynh.vuongg@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: quynh.vuongg@gmail.com
    auth_identity: quynh.vuongg@gmail.com
    auth_password: <pass>
    send_resolved: true
   