global:  
  scrape_interval:  15s   
  external_labels: 
      dc: 'node2' 

scrape_configs:  
      - job_name: 'prometheus'  
        static_configs: 
             - targets: ['prometheus1:9090','prometheus2:9091']

      - job_name: 'alertmanager'  
        static_configs: 
             - targets: ['alertmanager1:9093','alertmanager2:9095']


rule_files:  
  - "rule_files"

alerting:
  alert_relabel_configs:
    - source_labels: [dc]
      regex: (.+)\d+
      target_label: dc
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager1:9093
      - alertmanager2:9095
