global:  
  scrape_interval:  15s   
  external_labels: 
      monitor:  'my-monitor'  

scrape_configs:  
  - job_name: 'prometheus'  

    static_configs: 
         - targets: ['localhost:9090']

  - job_name: 'node-exporter'

    static_configs:
         - targets: ['node-exporter:9100']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
         - targets:
           - cadvisor:8080

rule_files:  
  - "rule_files"
